"""SEGPILOT live site: results dashboard + a real compression demo.

    uvicorn web.backend.main:app --reload      # local dev
    uvicorn web.backend.main:app --host 0.0.0.0 --port $PORT   # Render

Two things live here:

  GET  /api/results     serves results.json (generated by
                         `segpilot.replay.report --json`), the numbers the
                         dashboard renders. Single source of truth: the replay
                         harness, never hand-typed into the frontend.

  POST /api/compress     submits a real Paritok hosted-GPU compression job on
  GET  /api/compress/:id visitor-supplied text, async (submit + poll) because
                         we have measured the hosted GPU cold-starting for
                         minutes at a time, which would blow through any
                         synchronous request timeout.

The compress demo runs TWO compressions per submission -- baseline (no kind, no
intent, what Paritok's hosted path defaults to) and SEGPILOT (kind + intent
routed) -- so a visitor sees the actual lever from docs/findings.md work on
their own text, not a canned example.
"""

from __future__ import annotations

import os
from pathlib import Path

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from paritok.strategies.gpu_server import GpuServerStrategy
from paritok.token_counter import count_tokens

from segpilot.config import SegpilotConfig
from segpilot.policy.guard import score_retention, strip_ref_tag

from .jobs import JobStore
from .ratelimit import RateLimiter

BASE_DIR = Path(__file__).resolve().parent.parent   # web/
STATIC_DIR = BASE_DIR / "static"
RESULTS_JSON = BASE_DIR / "results.json"

MAX_CODE_CHARS = 4000
MAX_INTENT_CHARS = 300
ALLOWED_KINDS = ("file_read", "log_output", "bash_command", "assistant_thinking")

app = FastAPI(title="SEGPILOT")

_cfg = SegpilotConfig.load()
_strategy: GpuServerStrategy | None = None
_jobs = JobStore()
_limiter = RateLimiter(
    per_ip_max=int(os.environ.get("SEGPILOT_PER_IP_MAX", "5")),
    per_ip_window_s=float(os.environ.get("SEGPILOT_PER_IP_WINDOW_S", "60")),
    daily_max=int(os.environ.get("SEGPILOT_DAILY_MAX", "200")),
)


def _get_strategy() -> GpuServerStrategy:
    global _strategy
    if _strategy is None:
        if _cfg.paritok.require_api_key and not _cfg.paritok.api_key:
            raise RuntimeError(
                "PARITOK_API_KEY not set on the server -- the live demo cannot run."
            )
        _strategy = GpuServerStrategy(_cfg.to_paritok_config().gpu_server)
    return _strategy


class CompressRequest(BaseModel):
    code: str = Field(..., min_length=1, max_length=MAX_CODE_CHARS)
    intent: str = Field("", max_length=MAX_INTENT_CHARS)
    kind: str = Field("file_read")


def _client_ip(request: Request) -> str:
    # Render (and most PaaS) put the real client IP in X-Forwarded-For.
    fwd = request.headers.get("x-forwarded-for")
    if fwd:
        return fwd.split(",")[0].strip()
    return request.client.host if request.client else "unknown"


def _run_compress_job(code: str, intent: str, kind: str) -> dict:
    """The actual work, run in a background thread by JobStore.

    Two real Paritok hosted-GPU calls: one with no kind/intent (what the
    hosted path defaults to -- finding #5), one with both routed. Both are
    scored against the same must-keep definition so the comparison is apples
    to apples.
    """
    strategy = _get_strategy()
    original_tokens = count_tokens(code)

    baseline_raw = strategy.compress(code, query=None, kind=None)
    baseline = strip_ref_tag(baseline_raw)
    baseline_tokens = count_tokens(baseline)
    baseline_retention = score_retention(code, baseline_raw, kind=kind)

    routed_raw = strategy.compress(code, query=intent or None, kind=kind)
    routed = strip_ref_tag(routed_raw)
    routed_tokens = count_tokens(routed)
    routed_retention = score_retention(code, routed_raw, kind=kind)

    return {
        "original_tokens": original_tokens,
        "baseline": {
            "text": baseline,
            "tokens": baseline_tokens,
            "ratio": round(baseline_tokens / original_tokens, 3) if original_tokens else 1.0,
            "must_keep_retention": round(baseline_retention.retention, 3),
            "must_keep_total": baseline_retention.total,
        },
        "segpilot": {
            "text": routed,
            "tokens": routed_tokens,
            "ratio": round(routed_tokens / original_tokens, 3) if original_tokens else 1.0,
            "must_keep_retention": round(routed_retention.retention, 3),
            "must_keep_total": routed_retention.total,
            "kind": kind,
            "intent": intent,
        },
    }


@app.get("/api/health")
def health():
    ok, message = False, "not checked"
    try:
        ok, message = _get_strategy().check()
    except RuntimeError as exc:
        message = str(exc)
    return {"gpu_available": ok, "message": message, "rate_limit": _limiter.stats()}


@app.get("/api/results")
def results():
    if not RESULTS_JSON.exists():
        raise HTTPException(
            404,
            "results.json not generated yet -- run "
            "`python -m segpilot.replay.report --json --out web/results.json`",
        )
    return FileResponse(RESULTS_JSON, media_type="application/json")


@app.post("/api/compress")
def submit_compress(req: CompressRequest, request: Request):
    if req.kind not in ALLOWED_KINDS:
        raise HTTPException(400, f"kind must be one of {ALLOWED_KINDS}")

    decision = _limiter.check(_client_ip(request))
    if not decision.allowed:
        return JSONResponse(
            status_code=429,
            content={"error": decision.reason, "retry_after_s": round(decision.retry_after_s)},
        )

    job_id = _jobs.submit(lambda: _run_compress_job(req.code, req.intent, req.kind))
    return {"job_id": job_id}


@app.get("/api/compress/{job_id}")
def poll_compress(job_id: str):
    job = _jobs.get(job_id)
    if job is None:
        raise HTTPException(404, "unknown job id (it may have expired)")
    if job.status == "error":
        return {"status": "error", "error": job.error}
    if job.status == "done":
        return {"status": "done", "result": job.result}
    return {"status": job.status}


# Static site last, so it doesn't shadow the /api/* routes above.
if STATIC_DIR.exists():
    app.mount("/", StaticFiles(directory=str(STATIC_DIR), html=True), name="static")
