"""JSON export of the replay report, for the live site's dashboard.

The site's `/api/results` endpoint serves the file this writes, verbatim. It is
the single source of truth for every number the dashboard shows -- generated by
the same replay harness that produces the Markdown report and docs/results.md,
never hand-typed into frontend code.
"""

from __future__ import annotations

import json
from pathlib import Path

from segpilot.replay.harness import SessionReplay, aggregate
from segpilot.replay.metrics import ArmMetrics
from segpilot.replay.report import population_of

# Findings and corrections are prose, not computed numbers, so they are not
# derived from a measurement -- they are transcribed once from docs/findings.md
# and docs/results.md and kept in sync by hand. Everything numeric below comes
# from ArmMetrics.
FINDINGS = [
    "Hosted GPU silently ignores level — and accepts \"BANANA\" with HTTP 200",
    "Compression cache is blind to kind/level, collapsing any per-segment policy",
    "Hosted endpoint does not validate API keys → silently unattributed usage",
    "Intent dominates compression, but stock passes one stale intent per request",
    "tag_messages/assign_level are dead code; hosted path sends kind: null",
    "Proxy hardcodes /v1, breaking Gemini/OpenRouter/Groq-style base URLs",
    "Documented tools/view_trace.py does not exist (we wrote one)",
    "shadow_storage: \"redis\" validates but is unimplemented → silent data loss",
    "The two kind classifiers disagree; the conversation-aware one mislabels every file read",
]

CORRECTIONS = [
    {
        "was": "79% fewer tokens / 3.1× on a drift session",
        "why": "A hand-constructed example, not a benchmark result — the real agent sessions didn't reproduce it.",
    },
    {
        "was": "1.61× rel/1k on the drift session",
        "why": "An artefact of a cache poisoned during a hosted-GPU outage: passthrough segments were cached as if compressed. Fixed and re-run to a clean pass.",
    },
]


def _arm_dict(m: ArmMetrics) -> dict:
    return {
        "arm": m.arm,
        "ratio": round(m.ratio, 3),
        "saving_pct": round(m.saving_pct, 3),
        "must_keep_retention": round(m.mustkeep_retention, 3),
        "task_retention": round(m.task_retention, 3),
        "rel_per_1k": round(m.task_relevance_per_1k, 3),
        "guard_trips": m.guard_trips,
        "sessions": m.sessions,
        "original_tokens": m.original_tokens,
        "compressed_tokens": m.compressed_tokens,
    }


def build_json_report(
    totals: dict[str, ArmMetrics],
    replays: list[SessionReplay],
    arms: list[str],
    *,
    solve_rate: dict[str, tuple[int, int]] | None = None,
    adaptive_note: str | None = None,
) -> dict:
    by_pop: dict[str, list[SessionReplay]] = {"campaign": [], "single-bug": []}
    for r in replays:
        by_pop[population_of(r.task_id)].append(r)

    populations = {}
    for pop, subset in by_pop.items():
        if not subset:
            continue
        pop_totals = aggregate(subset, arms)
        populations[pop] = {
            "session_count": len(subset),
            "arms": [_arm_dict(pop_totals[a]) for a in arms if a in pop_totals],
        }

    per_task = [
        {
            "task_id": r.task_id,
            "population": population_of(r.task_id),
            "arms": [_arm_dict(r.per_arm[a]) for a in arms if a in r.per_arm],
        }
        for r in replays
    ]

    doc = {
        "generated_from_sessions": len(replays),
        "arms": arms,
        "aggregate_all": [_arm_dict(totals[a]) for a in arms if a in totals],
        "populations": populations,
        "per_task": per_task,
        "findings": FINDINGS,
        "corrections": CORRECTIONS,
        "verdict": (
            "Intent/kind routing does not reliably beat Paritok's stock defaults. "
            "kind_only equals stock everywhere; intent routing is weak "
            "(~+9pp must-keep on drift sessions) and inconsistent (reverses on "
            "some sessions). Task-relevant retention barely moves, so rel/1k is "
            "flat and reflects mostly how hard each arm compressed."
        ),
    }
    if solve_rate:
        doc["solve_rate"] = {
            arm: {"solved": s, "total": t, "rate": round(s / t, 3) if t else None}
            for arm, (s, t) in solve_rate.items()
        }
    if adaptive_note:
        doc["adaptive_note"] = adaptive_note
    return doc


def write_json_report(
    totals: dict[str, ArmMetrics],
    replays: list[SessionReplay],
    arms: list[str],
    *,
    out_path: str | Path,
    solve_rate: dict[str, tuple[int, int]] | None = None,
    adaptive_note: str | None = None,
) -> Path:
    doc = build_json_report(
        totals, replays, arms, solve_rate=solve_rate, adaptive_note=adaptive_note
    )
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")
    return path
